apiVersion: v1
kind: ReplicationController
metadata:
  name: testapp
  labels:
    app: testapp
    version: v1
spec:
  replicas: 8
  selector:
    app: testapp
    version: v1
  template:
    metadata:
      labels:
        app: testapp
        version: v1
    spec:
      containers:
        - name: testapp
          image: testapp:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 3000